### ISSUE TITLE
Setup Script for Databricks doesn't work

### ISSUE THREAD

**Issue by lorenzkort** [MicrosoftLearning/mslearn-databricks#60] opened 2024-10-15 07:42 UTC
![Screenshot 2024-10-15 at 09 43 15](https://github.com/user-attachments/assets/7603080d-2c68-4223-8739-c603c41e2e94)

I don't have any active policies, this is on my personal Azure Portal

https://microsoftlearning.github.io/mslearn-databricks/Instructions/Exercises/LA-01-Explore-Azure-Databricks.html

https://github.com/MicrosoftLearning//mslearn-databricks/setup.ps1

**Comment by madiepev** [comment] 2024-10-25 11:05
Hi @lorenzkort could you try creating the workspace in a different region?

**Comment by lorenzkort** [comment] 2024-10-25 11:11
Already tried without success

**Comment by madiepev** [comment] 2024-10-25 11:37
I wasn't able to reproduce the error across multiple subscriptions. 
This seems to be a quota issue specifically for your subscription. Note that the setup script checks whether there is available quote for specific VM SKUs in the listed regions. 

You can check your available quotas across regions in your subscription, and either change the quota if it's a soft limit, or choose a different VM size/region to one that is available to you. 

Alternatively, you can use the Portal UI to create an Azure Databricks workspace to continue with the exercise. When asked to create compute, I'd recommend to just use whatever compute is available to you. 

Hope that helps!

**Comment by lorenzkort** [comment] 2024-10-26 08:35
I haven't been able to test it, but maybe it's something you could include in the powershell script so that users who encounter this error are automatically directed to the right region which works for them? Or throw the right error so that users know what to do in order to solve it?

**Comment by madiepev** [comment] 2024-10-28 09:05
Thanks for your suggestions.  I'll close this issue for now, but let us know if you continue encountering issues.

**Closed by madiepev** 2024-10-28 09:05 UTC

**Comment by lorenzkort** [comment] 2024-10-28 09:21
I think it's quite lazy to not build this in and just closing the ticket like this. Many people have this issue on MS learn

**Comment by madiepev** [comment] 2024-10-28 09:28
We already built in the script that multiple regions are checked for availability of specific virtual machine sizes and the screenshot you shared shows the error that your subscription has no available quota, which indicates a problem with the specific subscription you're using. I offered you multiple suggestions for solutions to a problem that seems to be specific to your Azure subscription. You indicated you had no time to test it yet. To avoid the issue going stale, I'm closing the issue as multiple solutions were already provided to a problem you personally have, but is not a problem of the content in this repo. You are very welcome to continue using this issue to allow us to help you troubleshoot, but currently, it doesn't appear to be an issue with the content.
Did you hear about other people having this issue? Could you provide more details as to what they're experiencing? Did they try the suggestions listed above and did that solve the issue?
